name: ano-dev-${USER}
services:
  ano-dev:
    image: ${IMAGE_FULL}:latest
    pull_policy: never
    volumes:
      - .:/mnt/current_folder:cached
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - USERNAME=${USER:-developer}
      - USERID=${USER_ID:-1000}
      - GROUPID=${GROUP_ID:-1000}
    tty: true
    stdin_open: true
    entrypoint: ["/entrypoint.sh", "sleep", "infinity"]
