name: gpu-algo-dev-${USER}
services:
  gpu-algo-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER:-developer}
        USERID: ${USER_ID:-1000}
        GROUPID: ${GROUP_ID:-1000}
    image: mikesrnd/gpu-algo-dev:latest
    pull_policy: missing
    volumes:
      - .:/mnt/current_folder:cached
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - USERNAME=${USER:-developer}
      - USERID=${USER_ID:-1000}
      - GROUPID=${GROUP_ID:-1000}
    tty: true
    stdin_open: true
    entrypoint: ["/entrypoint.sh", "sleep", "infinity"]
    cpus: "0.5"
